pipeline {
    agent { node { label 'Agent-1' } }

    stages {
        stage('init') {
            steps {
                echo 'initializing..'
                sh '''
                 ls -ltr
                 pwd

                '''
            }
        }
        stage('planning') {
            steps {
                echo 'planning..'
                 sh '''
                 ls -ltr
                 pwd
                 
                '''
            }
        }
    }
    post { 
        always { 
            echo 'it will always run whether it is success or not'
        }
        success{
            echo 'it will run if it is success'
        }
        failure{
            echo 'it will run if it is failure'
        }
    }
}
