pipeline {
    agent { node { label 'Agent-1' } }
     options {
        ansiColor('xterm')
    }

    stages {
        stage('init') {
            steps {
                echo 'initializing..'
                sh '''
                 pwd
                 ls -ltr
                 cd 01-Vpc
                 terraform init

                '''
            }
        }
        stage('planning') {
            steps {
                echo 'planning..'
                 sh '''
                 pwd
                 ls -ltr
                 cd 01-Vpc
                 terraform plan
                '''
            }
        }
        stage('Approve') {
            steps {
                input 'shall i apply?'
            }
        }
    }
    post { 
        always { 
            echo 'it will always run whether it is success or not'
        }
        success{
            echo 'it will run if it is success'
        }
        failure{
            echo 'it will run if it is failure'
        }
    }
}
